export type MediaType = "image" | "video" | "document";

export type MediaStatus =
  | "active"
  | "reusable"
  | "registered"
  | "unused"
  | "unknown"
  | "duplicate-candidate"
  | "safe-to-archive-later";

export type MediaRecord = {
  src: string;
  poster?: string;
  mediaType: MediaType;
  width?: number;
  height?: number;
  destination: string;
  role: string;
  alt: string;
  status: MediaStatus;
  futureCanonicalKey?: string;
};

const cdn = (path: string) => `https://cdn.hob.farm/${path}`;

/**
 * Logical index for existing HobFarm CDN objects.
 *
 * The keys are stable page-facing identifiers. The source paths remain at their
 * current R2 locations until a separate migration is reviewed and approved.
 */
export const mediaRegistry = {
  "ezize.app.private-alpha": {
    src: "/media/ezize/ezize-app-private-alpha-640.webp",
    mediaType: "image",
    width: 640,
    height: 1170,
    destination: "/ezize/",
    role: "private-alpha-application-proof",
    alt: "EZIZE private-alpha generation window showing a completed Corrupted Cake pull, its persona, form, exact odds, deterministic identity, and rendered image",
    status: "active",
  },
  "ezize.output.corrupted-cake": {
    src: "/media/ezize/ezize-corrupted-cake-1200.webp",
    mediaType: "image",
    width: 1200,
    height: 1800,
    destination: "/ezize/",
    role: "generated-output-proof",
    alt: "Corrupted Cake generated by EZIZE with black and cream icing, mushrooms, fruit, dark flowers, and toxic green light in a gothic laboratory",
    status: "active",
  },
  "stylefusion.banner.image": {
    src: cdn("pages/projects/images/stylefusion-banner.jpg"),
    mediaType: "image",
    destination: "/workshop/stylefusion/",
    role: "hero-poster",
    alt: "StyleFusion reference-analysis workspace banner",
    status: "active",
    futureCanonicalKey: "workshop/stylefusion/banner",
  },
  "stylefusion.banner.video": {
    src: cdn("pages/projects/images/stylefusion-banner-video.mp4"),
    poster: cdn("pages/projects/images/stylefusion-banner.jpg"),
    mediaType: "video",
    destination: "/workshop/stylefusion/",
    role: "hero-motion",
    alt: "StyleFusion workflow banner in motion",
    status: "active",
    futureCanonicalKey: "workshop/stylefusion/banner-video",
  },

  "stylefusion.cathedral.v1": processImage("book", "book-v1.jpg", "generated-variant", "Blue-eyed tuxedo cat in the first engraved Cathedral Cat landscape"),
  "stylefusion.cathedral.v2": processImage("book", "book-v2.png", "generated-variant", "Blue-eyed tuxedo cat before a monumental skull in the second Cathedral Cat variant"),
  "stylefusion.cathedral.v3": processImage("book", "book-v3.png", "generated-variant", "Blue-eyed tuxedo cat in the third Cathedral Cat engraved landscape"),
  "stylefusion.cathedral.v4": processImage("book", "book-v4.png", "generated-variant", "Blue-eyed tuxedo cat and skull landscape in the fourth Cathedral Cat variant"),
  "stylefusion.cathedral.cover": processImage("book", "book-cover.png", "downstream-cover", "The Star in the Skull downstream book-cover study"),
  "stylefusion.cathedral.hero": processImage("book", "book-hero.png", "downstream-hero", "Cathedral Cat hero image with a tuxedo cat before a towering skull gate"),
  "stylefusion.cathedral.video": processVideo("book", "book-video.mp4", "book-hero.png", "downstream-motion", "Cathedral Cat downstream motion study"),
  "stylefusion.cathedral.export": processDocument("book", "ir-large-black-white-cat-1778847195673.txt", "complete-export", "Cathedral Cat Complete Export record"),

  "stylefusion.hellcat.v1": processImage("motion", "motion-v1.png", "generated-variant", "Hellcat generated variant in a burning industrial complex"),
  "stylefusion.hellcat.v2": processImage("motion", "motion-v2.png", "generated-variant", "Hellcat generated variant with green eyes and industrial firelight"),
  "stylefusion.hellcat.v3": processImage("motion", "motion-v3.jpg", "generated-variant", "Hellcat generated anime-style industrial variant"),
  "stylefusion.hellcat.v4": processImage("motion", "motion-v4.png", "generated-variant", "Hellcat generated variant in the Iron Wastes"),
  "stylefusion.hellcat.hero": processImage("motion", "motion-hero.png", "downstream-hero", "Hellcat neon-industrial hero portrait"),
  "stylefusion.hellcat.poster": processImage("motion", "motion-poster.png", "downstream-poster", "Hellcat of the Iron Wastes pulp poster"),
  "stylefusion.hellcat.video-poster": processImage("motion", "motion-video-poster.jpg", "video-poster", "Hellcat promotional video poster"),
  "stylefusion.hellcat.video": processVideo("motion", "motion-video.mp4", "motion-video-poster.jpg", "downstream-motion", "Hellcat of the Iron Wastes promotional motion study"),
  "stylefusion.hellcat.export": processDocument("motion", "ir-primary-subject-elf-like-female-1778851549214.txt", "complete-export", "Hellcat Complete Export record"),

  "character.fashion.v1": characterImage("fashion-v1.jpg", "generated-variant", "Fashion character study, variant one"),
  "character.fashion.v2": characterImage("fashion-v2.png", "generated-variant", "Fashion character study, variant two"),
  "character.fashion.v3": characterImage("fashion-v3.png", "generated-variant", "Fashion character study, variant three"),
  "character.fashion.v4": characterImage("fashion-v4.jpg", "generated-variant", "Fashion character study, variant four"),
  "character.fashion.sheet": characterImage("fashion-sheet.png", "character-sheet", "Fashion character production sheet"),
  "character.fashion.hero": characterImage("fashion-hero.png", "hero", "Fashion character hero image"),
  "character.fashion.poster": characterImage("fashion-poster.jpg", "poster", "Fashion character production poster"),
  "character.fashion.og": characterImage("fashion-og.jpg", "social-preview", "Fashion character social preview"),
  "character.fashion.video": characterVideo("fashion-video.mp4", "fashion-poster.jpg", "motion", "Fashion character motion study"),
  "character.fashion.export": characterDocument("ir-stylized-female-figure-stands-1778822091644.txt", "complete-export", "Fashion character Complete Export record"),

  "character.generic-37.base": conceptImage("stylefusion-concept1.jpg", "generic-base", "Generic Female number 37 base character"),
  "character.generic-37.result": conceptImage("stylefusion-concept2.jpg", "designed-result", "Designed result developed from Generic Female number 37"),
  "character.generic-37.face": conceptImage("stylefusion-face.jpg", "face-decision", "Face decisions for Generic Female number 37"),
  "character.generic-37.color": conceptImage("stylefusion-color.jpg", "color-decision", "Color decisions for Generic Female number 37"),
  "character.generic-37.texture": conceptImage("stylefusion-texture.jpg", "texture-decision", "Texture decisions for Generic Female number 37"),
  "character.generic-37.intent": conceptImage("stylefusion-intent.jpg", "intent-record", "Intent decisions for Generic Female number 37"),
  "character.generic-37.negative": conceptImage("stylefusion-negative.jpg", "exclusion-guidance", "Exclusion guidance for Generic Female number 37"),
  "character.generic-37.video": conceptVideo("stylefusion-concept-vid.mp4", "stylefusion-concept2.jpg", "motion-result", "Generic Female number 37 motion result"),

  "avatar.identity.hillary": workshopImage("images/hillary01.WEBP", "/workshop/avatar-host/", "canonical-profile", "Hillary, the HobFarm editorial and Workshop host", 1280, 1920),
  "avatar.identity.ami": workshopImage("images/ami01.WEBP", "/workshop/avatar-host/", "canonical-profile", "Ami, the HobFarm social and commercial presenter", 1280, 1920),
  "avatar.identity.em": workshopImage("images/em01.jpg", "/workshop/workshop-notes/psygoth/", "canonical-profile", "Em, the green growth lane of the PsyGoth presenter trio", 1792, 2368),
  "avatar.identity.nina": workshopImage("images/nina01.jpg", "/workshop/workshop-notes/psygoth/", "canonical-profile", "Nina, the red pressure lane of the PsyGoth presenter trio", 1792, 2368),
  "avatar.identity.zima": workshopImage("images/zima01.WEBP", "/workshop/workshop-notes/psygoth/", "canonical-profile", "Zima, the blue structure lane of the PsyGoth presenter trio", 1280, 1920),
  "avatar.identity.hobgal": workshopImage("images/hobgal01.jpg", "/workshop/avatar-host/", "historical-profile", "Hobgal, the retired early HobFarm presenter prototype", 1664, 2496, "safe-to-archive-later"),
  "workshop.graphics.hero": workshopImage("images/workshop-hero.png", "/workshop/", "section-hero", "A long Workshop table covered with source books, drawings, character studies, camera gear, lighting, and portals into finished worlds", 1672, 941),
  "workshop.method.research-source": workshopMethodImage("01-research-the-source.webp", "Archive books, photographs, sketches, and a magnifying glass arranged around a neutral mannequin on a Workshop table"),
  "workshop.method.define-base": workshopMethodImage("02-define-the-base.webp", "A neutral mannequin measured against front and profile drawings on a calibrated Workshop platform"),
  "workshop.method.build-transformation": workshopMethodImage("03-build-the-transformation.webp", "A neutral mannequin passes through a mechanical rig and emerges with clothing, materials, color, and a miniature world"),
  "workshop.method.direct-result": workshopMethodImage("04-direct-the-result.webp", "A camera, two lights, and framing cards direct a mannequin inside a practical miniature set"),
  "workshop.method.publish-extend": workshopMethodImage("05-publish-and-extend.webp", "One finished work connects to a book, framed print, screen, product box, and projected miniature scene"),
  "workshop.program-index.character-mannequin": workshopProgramIndexImage("character-mannequin.webp", "/workshop/character-mannequin/", "A wooden artist mannequin surrounded by material swatches, model studies, object maquettes, and a miniature set"),
  "workshop.program-index.avatar-host": workshopProgramIndexImage("avatar-host.webp", "/workshop/avatar-host/", "A wooden artist mannequin staged with a camera, microphone, lights, monitor, and clapboard for a host production"),
  "workshop.program-index.before-after": workshopProgramIndexImage("before-after.webp", "/workshop/before-and-after/", "The same utility room held in one camera view, aged and abandoned on one side and carefully restored on the other"),
  "workshop.program-index.cute-corrupted": workshopProgramIndexImage("cute-corrupted.webp", "/workshop/cute-and-corrupted/", "Matching rabbit sculptures shown in a clean pastel mode and a cracked dark corrupted mode"),
  "workshop.program-index.alter-ego": workshopProgramIndexImage("alter-ego.webp", "/workshop/alter-ego/", "Two wooden artist mannequins built from the same model and directed as bright and dark stage personas"),
  "workshop.route-card.publication": workshopRouteCardImage("publication.webp", "/articles/", "An editor's worktable with an open folio, photographic print, gallery frame, sequencing cards, and binding tools"),
  "workshop.route-card.motion-social": workshopRouteCardImage("motion-social.webp", "/presents/", "A miniature motion stage with a camera, storyboard frames, vertical display, carousel cards, and controlled light trails"),
  "workshop.route-card.marketplace": workshopRouteCardImage("marketplace.webp", "/shop/", "A curated packing and display bench with image folios, template cards, edition sleeves, a parcel box, and shelf presentation"),
  "workshop.route-card.academy": workshopRouteCardImage("academy.webp", "/academy/", "A teaching workbench with a wooden mannequin, step cards, source packet, notebook, template sheets, and a focused lamp"),
  "workshop.route-card.applications-studio": workshopRouteCardImage("applications-studio.webp", "/workshop/stylefusion/", "An application and studio workbench with an abstract interface, miniature set, compositing plates, light grid, and finishing tools"),
  "workshop.route-card.stylefusion": workshopRouteCardImage("stylefusion.webp", "/workshop/stylefusion/", "A reference-analysis bench organizing photo cards into color, material, lighting, and composition decisions"),
  "workshop.route-card.wonder-machine": workshopRouteCardImage("wonder-machine.webp", "/presents/other-alice-adventures/", "A theatrical story machine with branching doorways, route tokens, character-memory cards, and a glowing mechanical orrery"),
  "workshop.route-card.voice-avatar-production": workshopRouteCardImage("voice-avatar-production.webp", "/workshop/avatar-host/", "A wooden mannequin in a compact recording booth with a microphone, camera, lights, pose cards, and caption monitor"),
  "workshop.route-card.image-motion-delivery": workshopRouteCardImage("image-motion-delivery.webp", "/workshop/workshop-notes/", "A finishing bench with photographic strips, motion frames, an edit timeline, compositing layers, and prepared output cases"),
  "workshop.graphics.landing": workshopImage("images/workshop.png", "/workshop/", "section-hero", "The HobFarm Workshop host system, character sheet, process inspector, storyboards, media registry, and motion test", 1672, 941),
  "workshop.graphics.hillary": workshopImage("images/workshop-hillary.png", "/workshop/ and /workshop/avatar-host/", "editorial-host-system", "Hillary at the center of HobFarm articles, Presents, Workshop, and in-progress productions", 1672, 941),
  "presents.graphics.avatar-system": workshopImage("images/presents-with-avatars.png", "/presents/", "section-hero", "HobFarm Presents programs with Hillary, Ami, Em, Nina, and Zima as recurring editorial hosts", 1672, 941),
  "workshop.alter-ego.poster": {
    src: cdn("visual-systems/sophia-stella-poster-hd.jpg"),
    mediaType: "image",
    destination: "/workshop/alter-ego/",
    role: "paired-persona-poster",
    alt: "Sophia and Stella Alter Ego paired-persona poster",
    status: "active",
  },
  "workshop.character-mannequin.workflow": {
    src: "/media/workshop/character-mannequin/mannequin-to-character-workflow.png",
    mediaType: "image",
    destination: "/ and /workshop/character-mannequin/",
    role: "pre-character-workflow",
    alt: "Mannequin-to-character workflow showing proportions, a neutral base, face and hair options, wardrobe, scene direction, camera tests, and motion output",
    status: "active",
    width: 1254,
    height: 1254,
  },
  "workshop.character-mannequin.home.brief": {
    src: "/media/workshop/character-mannequin/homepage-stages/brief-or-portrait.webp",
    mediaType: "image",
    destination: "/ and /workshop/character-mannequin/",
    role: "homepage-brief-stage",
    alt: "Anonymous studio mannequin surrounded by proportion studies, neutral swatches, and identity markers",
    status: "active",
    width: 800,
    height: 1000,
  },
  "workshop.character-mannequin.home.neutral-system": {
    src: "/media/workshop/character-mannequin/homepage-stages/neutral-system.webp",
    mediaType: "image",
    destination: "/ and /workshop/character-mannequin/",
    role: "homepage-neutral-system-stage",
    alt: "Neutral full-body mannequin with modular wardrobe, head, hand, camera, and motion studies",
    status: "active",
    width: 800,
    height: 1000,
  },
  "workshop.character-mannequin.home.visual-language": {
    src: "/media/workshop/character-mannequin/homepage-stages/visual-language.webp",
    mediaType: "image",
    destination: "/ and /workshop/character-mannequin/",
    role: "homepage-visual-language-stage",
    alt: "Neutral mannequin bust with hair, makeup, garment, material, palette, and symbol studies",
    status: "active",
    width: 800,
    height: 1000,
  },
  "workshop.character-mannequin.home.character-profile": {
    src: "/media/workshop/character-mannequin/homepage-stages/character-profile.webp",
    mediaType: "image",
    destination: "/ and /workshop/character-mannequin/",
    role: "homepage-character-profile-stage",
    alt: "Finished original character portrait with subtle profile and rear continuity diagrams",
    status: "active",
    width: 800,
    height: 1000,
  },
  "workshop.character-mannequin.home.motion-proof": {
    src: "/media/workshop/character-mannequin/homepage-stages/motion-proof.webp",
    mediaType: "image",
    destination: "/ and /workshop/character-mannequin/",
    role: "homepage-motion-proof-stage",
    alt: "Original character performing a directed gesture on a camera and motion test stage",
    status: "active",
    width: 800,
    height: 1000,
  },
  "workshop.character-mannequin.workflow-film": {
    src: "/media/workshop/character-mannequin/mannequin-workflow-film.mp4",
    poster: "/media/workshop/character-mannequin/mannequin-workflow-film-poster.png",
    mediaType: "video",
    destination: "/workshop/character-mannequin/",
    role: "pre-character-system-film",
    alt: "Motion study showing a stable mannequin base, variable identity layers, and continuity tests through camera, scene, and motion",
    status: "active",
    width: 1920,
    height: 1080,
  },
  "workshop.character-mannequin.workflow-film-poster": {
    src: "/media/workshop/character-mannequin/mannequin-workflow-film-poster.png",
    mediaType: "image",
    destination: "/workshop/character-mannequin/",
    role: "pre-character-system-film-poster",
    alt: "Complete mannequin-to-character continuity board beside the statement that one approved base can carry many identities",
    status: "active",
    width: 1920,
    height: 1080,
  },
  "other-alice.wonderland.world-map": {
    src: "/media/other-alice/other-alice-wonderland-world-map.png",
    mediaType: "image",
    destination: "/ and /presents/other-alice-adventures/",
    role: "developing-world-map",
    alt: "Developing map of Other Alice's Wonderland with concentric regions, routes, portals, House influences, the Wasteland, and the Park Anomaly",
    status: "active",
    width: 1448,
    height: 1086,
  },
  "other-alice.alice.representative-landscape": {
    src: "/media/other-alice/alice-bio/alice-representative-landscape-v1.webp",
    mediaType: "image",
    destination: "/ and /presents/other-alice-adventures/",
    role: "representative-world-scene",
    alt: "Other Alice at the threshold of her working cabin, holding a prepared remedy while rain falls across a wet mushroom route",
    status: "active",
    width: 1920,
    height: 1080,
  },
  "other-alice.alice.first-home": {
    src: "/media/other-alice/alice-bio/alice-chester-first-home-v1.webp",
    mediaType: "image",
    destination: "/ and /presents/other-alice-adventures/cast/alice/",
    role: "campaign-consequence-scene",
    alt: "Other Alice outside her working cabin as Chester blocks a wet route through the garden",
    status: "active",
    width: 1800,
    height: 1200,
  },
  "other-alice.alice.size-change": {
    src: "/media/other-alice/alice-bio/alice-size-changing-access-v1.webp",
    mediaType: "image",
    destination: "/presents/other-alice-adventures/cast/alice/",
    role: "conditional-access-scene",
    alt: "A six-inch-tall Other Alice investigates a leaking root-pipe beside a thimble, thread spool, needle, and iron fittings",
    status: "active",
    width: 1800,
    height: 1200,
  },
  "other-alice.alice.workshop": {
    src: "/media/other-alice/alice-bio/alice-workshop-local-effect-v1.webp",
    mediaType: "image",
    destination: "/presents/other-alice-adventures/cast/alice/",
    role: "authored-world-action-scene",
    alt: "Other Alice measures spores into resin while repairing a cracked living water filter at her workshop table",
    status: "active",
    width: 1920,
    height: 1080,
  },

  "before-after.shit-to-shine.source": beforeAfterMedia("abandoned-laundry.jpg", "image", "source-frame", "Abandoned laundry room with broken machines, standing water, exposed walls, and debris", undefined, 1920, 1440),
  "before-after.shit-to-shine.after": beforeAfterMedia("abandoned-laundry-after.jpg", "image", "final-frame", "The same laundry room rebuilt as a bright near-future utility space with fitted storage and three machines", undefined, 1660, 1244),
  "before-after.shit-to-shine.video": beforeAfterMedia("before-after-shit-to-shine.mp4", "video", "featured-transformation", "Locked-camera transformation from an abandoned laundry room to a rebuilt utility space", "abandoned-laundry-after.jpg", 1660, 1244),
  "before-after.north-shore.before": beforeAfterMedia("california-north-shore-yacht-club-1965.jpg", "image", "documentary-before", "Black-and-white archive view of the active North Shore marina with boats, palms, and the yacht club", undefined, 1920, 1440),
  "before-after.north-shore.after": beforeAfterMedia("california-north-shore-yacht-club-2010.jpg", "image", "documentary-after", "Later color view of the North Shore marina basin with the restored yacht club beyond the receded shoreline", undefined, 1920, 1440),
  "before-after.north-shore.video": beforeAfterMedia("california-north-shore-yacht-club-time-lapse.mp4", "video", "documentary-transition", "Transformation study between two documented views of the North Shore marina", "california-north-shore-yacht-club-1965.jpg", 1660, 1244),
  "before-after.salton-city.before": beforeAfterMedia("salton-city-1965.png", "image", "historical-source", "Black-and-white aerial source image of Salton City's street grid beside the Salton Sea", undefined, 6028, 4752),
  "before-after.salton-city.after": beforeAfterMedia("salton-city-2065.png", "image", "alternate-future", "Imagined 2065 Salton City developed into a dense solar, wind, and geothermal desert city", undefined, 1448, 1086),
  "before-after.salton-city.video": beforeAfterMedia("salton-city-1965-2065.mp4", "video", "counterfactual-transition", "Counterfactual transformation from the Salton City source frame to an imagined 2065 city", "salton-city-2065.png", 1620, 1276),

  "avatar-host.hillary.main.video": avatarHostPlaceholder("video", "hillary-main-presenter.mp4", "standardized-host-test", "Hillary main HobFarm presenter standardized host test"),
  "avatar-host.hillary.main.captions": avatarHostPlaceholder("document", "hillary-main-presenter.srt", "caption-sidecar", "SRT captions for Hillary's main HobFarm presenter test"),
  "avatar-host.hillary.workshop.video": avatarHostPlaceholder("video", "hillary-workshop-editor.mp4", "standardized-host-test", "Hillary Workshop technical editor standardized host test"),
  "avatar-host.hillary.workshop.captions": avatarHostPlaceholder("document", "hillary-workshop-editor.srt", "caption-sidecar", "SRT captions for Hillary's Workshop technical editor test"),
  "avatar-host.hillary.cinema.video": avatarHostPlaceholder("video", "hillary-cinema-host.mp4", "standardized-host-test", "Hillary HobFarm TV cinema host standardized host test"),
  "avatar-host.hillary.cinema.captions": avatarHostPlaceholder("document", "hillary-cinema-host.srt", "caption-sidecar", "SRT captions for Hillary's HobFarm TV cinema host test"),
  "avatar-host.ami.social.video": avatarHostPlaceholder("video", "ami-social-presenter.mp4", "standardized-host-test", "Ami social presenter standardized host test"),
  "avatar-host.ami.social.captions": avatarHostPlaceholder("document", "ami-social-presenter.srt", "caption-sidecar", "SRT captions for Ami's social presenter test"),
  "avatar-host.em.trio.video": avatarHostPlaceholder("video", "em-trio-presenter.mp4", "standardized-host-test", "Em green-lane trio presenter standardized host test"),
  "avatar-host.em.trio.captions": avatarHostPlaceholder("document", "em-trio-presenter.srt", "caption-sidecar", "SRT captions for Em's green-lane trio presenter test"),
  "avatar-host.nina.trio.video": avatarHostPlaceholder("video", "nina-trio-presenter.mp4", "standardized-host-test", "Nina red-lane trio presenter standardized host test"),
  "avatar-host.nina.trio.captions": avatarHostPlaceholder("document", "nina-trio-presenter.srt", "caption-sidecar", "SRT captions for Nina's red-lane trio presenter test"),
  "avatar-host.zima.trio.video": avatarHostPlaceholder("video", "zima-trio-presenter.mp4", "standardized-host-test", "Zima blue-lane trio presenter standardized host test"),
  "avatar-host.zima.trio.captions": avatarHostPlaceholder("document", "zima-trio-presenter.srt", "caption-sidecar", "SRT captions for Zima's blue-lane trio presenter test"),

  "avatar-host.hobgal.prototype.video": workshopMedia("avatar-host-system/hobgal-prototype.mp4", "video", "/workshop/avatar-host/", "retired-prototype", "Hobgal explains an early version of the HobFarm production system", "safe-to-archive-later", "avatar-host-system/hobgal-prototype.webp"),
  "avatar-host.hobgal.prototype.poster": workshopMedia("avatar-host-system/hobgal-prototype.webp", "image", "/workshop/avatar-host/", "retired-prototype-poster", "Hobgal retired prototype presenter frame", "safe-to-archive-later", undefined, 405, 720),
  "avatar-host.hobgal.prototype.transcript": workshopMedia("avatar-host-system/transcripts/hobgal-prototype.txt", "document", "/workshop/avatar-host/", "historical-transcript", "Transcript for the retired Hobgal prototype clip", "safe-to-archive-later"),

  "workshop.psygoth.em.video": workshopMedia("psygoth/em-primary.mp4", "video", "/workshop/workshop-notes/psygoth/", "primary-character-chapter", "Em defines the green lane of the PsyGoth system", "active", "psygoth/em-primary.webp"),
  "workshop.psygoth.em.poster": workshopMedia("psygoth/em-primary.webp", "image", "/workshop/workshop-notes/psygoth/", "video-poster", "Em in an illustrated green PsyGoth landscape", "active"),
  "workshop.psygoth.em.transcript": workshopMedia("psygoth/transcripts/em-primary.txt", "document", "/workshop/workshop-notes/psygoth/", "source-transcript", "Transcript for Em's primary PsyGoth chapter", "active"),
  "workshop.psygoth.nina.video": workshopMedia("psygoth/nina-primary.mp4", "video", "/workshop/workshop-notes/psygoth/", "primary-character-chapter", "Nina defines the red lane of the PsyGoth system", "active", "psygoth/nina-primary.webp"),
  "workshop.psygoth.nina.poster": workshopMedia("psygoth/nina-primary.webp", "image", "/workshop/workshop-notes/psygoth/", "video-poster", "Nina in a volcanic red PsyGoth landscape", "active"),
  "workshop.psygoth.nina.transcript": workshopMedia("psygoth/transcripts/nina-primary.txt", "document", "/workshop/workshop-notes/psygoth/", "source-transcript", "Transcript for Nina's primary PsyGoth chapter", "active"),
  "workshop.psygoth.zima.video": workshopMedia("psygoth/zima-primary.mp4", "video", "/workshop/workshop-notes/psygoth/", "primary-character-chapter", "Zima defines the blue lane of the PsyGoth system", "active", "psygoth/zima-primary.webp"),
  "workshop.psygoth.zima.poster": workshopMedia("psygoth/zima-primary.webp", "image", "/workshop/workshop-notes/psygoth/", "video-poster", "Zima in a blue ice-storm PsyGoth landscape", "active"),
  "workshop.psygoth.zima.transcript": workshopMedia("psygoth/transcripts/zima-primary.txt", "document", "/workshop/workshop-notes/psygoth/", "source-transcript", "Transcript for Zima's primary PsyGoth chapter", "active"),

  "workshop.psygoth.zima.design-v2": workshopMedia("mannequin-to-avatar/v2/stills/psygoth-zima-blue-v2.png", "image", "/ and /workshop/", "visual-language-outcome", "Zima in an ornate blue PsyGoth portrait with astral diagrams, ice crystals, smoke, lace, and polished vinyl", "active", undefined, 1024, 1536),
  "workshop.psygoth.nina.design-v2": workshopMedia("mannequin-to-avatar/v2/stills/psygoth-nina-red-v2.png", "image", "/workshop/", "visual-language-outcome", "Nina in an ornate red PsyGoth portrait with fire, sigils, black vinyl, chains, and gold hardware", "active", undefined, 1024, 1536),
  "workshop.psygoth.em.design-v2": workshopMedia("mannequin-to-avatar/v2/stills/psygoth-em-green-v2.png", "image", "/workshop/", "visual-language-outcome", "Em in an ornate green PsyGoth portrait with moss, crystal, insects, roots, lace, and botanical sigils", "active", undefined, 1024, 1536),

  "workshop.process.zima.mannequin": workshopMedia("mannequin-to-avatar/v1/stills/zima-neutral-mannequin-sheet-v1.png", "image", "/ and /workshop/", "process-stage", "Neutral Zima mannequin sheet with front, three-quarter, back, and face views", "active", undefined, 1672, 941),
  "workshop.process.zima.visual-language": workshopMedia("mannequin-to-avatar/v2/stills/psygoth-zima-blue-v2.png", "image", "/ and /workshop/", "process-stage", "Finished Zima PsyGoth Blue visual-language portrait", "active", undefined, 1024, 1536),
  "workshop.process.zima.wardrobe-board": workshopMedia("mannequin-to-avatar/v1/stills/zima-visual-language-wardrobe-v1.png", "image", "/ and /workshop/", "process-stage", "Zima visual-language and wardrobe board with eye, palette, material, character, and garment studies", "active", undefined, 1672, 941),
  "workshop.process.zima.vertical-poster": workshopMedia("mannequin-to-avatar/v2/posters/zima-process-film-vertical-poster-v2.jpg", "image", "/", "process-film-poster", "Vertical Zima mannequin-to-avatar Process Film poster", "active", undefined, 1080, 1920),
  "workshop.process.zima.vertical-video": workshopMedia("mannequin-to-avatar/v2/renders/zima-process-film-vertical-v2.mp4", "video", "/", "process-film", "Vertical Zima mannequin-to-avatar Process Film", "active", "mannequin-to-avatar/v2/posters/zima-process-film-vertical-poster-v2.jpg", 1080, 1920),
  "workshop.process.zima.wide-poster": workshopMedia("mannequin-to-avatar/v2/posters/zima-process-film-wide-poster-v2.jpg", "image", "/workshop/", "process-film-poster", "Wide Zima mannequin-to-avatar Process Film poster", "active", undefined, 1920, 1080),
  "workshop.process.zima.wide-video": workshopMedia("mannequin-to-avatar/v2/renders/zima-process-film-wide-v2.mp4", "video", "/workshop/", "process-film", "Wide Zima mannequin-to-avatar Process Film", "active", "mannequin-to-avatar/v2/posters/zima-process-film-wide-poster-v2.jpg", 1920, 1080),

  "workshop.ami-legacy.hero": workshopMedia("ami-legacy/legacy-ami-hero.webp", "image", "Ami Legacy campaign packet", "campaign-hero", "Ami presents the Legacy electric future wagon and robotic pulling system", "registered", undefined, 1672, 941),
  "workshop.ami-legacy.intro.video": workshopMedia("ami-legacy/Ami_Intro_with_captions.mp4", "video", "/workshop/future-carriage/ and /academy/avatar-content-system/", "avatar-introduction", "Ami introduces herself as a HobFarm avatar and welcomes viewers into the studio", "active", "images/ami01.WEBP", 1080, 1920),
  "workshop.ami-legacy.model-3917.ami": workshopMedia("ami-legacy/model-3917-ami.webp", "image", "Ami Legacy campaign packet", "campaign-key-art", "Ami beside the robot-pulled Model 3917 two-wheel carriage", "registered", undefined, 1672, 941),
  "workshop.ami-legacy.model-3917.vehicle": workshopMedia("ami-legacy/model-3917-vehicle.webp", "image", "Ami Legacy campaign packet", "vehicle-clean-plate", "Robot-pulled Model 3917 two-wheel carriage without a presenter", "registered", undefined, 1672, 941),
  "workshop.ami-legacy.autonomous-coach": workshopMedia("ami-legacy/autonomous-coach.webp", "image", "Ami Legacy campaign packet", "four-wheel-vehicle", "Four-wheel enclosed electric autonomous coach concept", "registered", undefined, 1672, 941),
  "workshop.ami-legacy.redwood-lifestyle": workshopMedia("ami-legacy/redwood-lifestyle.webp", "image", "Ami Legacy campaign packet", "lifestyle-scene", "Electric carriage traveling through a redwood forest", "registered", undefined, 1672, 941),
  "workshop.ami-legacy.redwood-profile": workshopMedia("ami-legacy/redwood-profile.webp", "image", "Ami Legacy campaign packet", "vehicle-profile", "Electric four-wheel carriage in profile among redwoods", "registered", undefined, 1672, 941),
  "workshop.ami-legacy.history.diligence": workshopMedia("ami-legacy/historical/diligence-coach.webp", "image", "Ami Legacy campaign packet", "historical-reference", "Historical diligence coach reference drawing", "reusable", undefined, 1920, 1235),
  "workshop.ami-legacy.history.gig-3917": {
    src: "/media/workshop/ami-legacy/historical/gig-3917.webp",
    mediaType: "image",
    destination: "Ami Legacy campaign packet",
    role: "historical-reference",
    alt: "Brewster and Company 1884 design drawing for Gig number 3917",
    status: "reusable",
    width: 1920,
    height: 1420,
  },
  "workshop.ami-legacy.history.stanhope": workshopMedia("ami-legacy/historical/stanhope-gig-3915.webp", "image", "Ami Legacy campaign packet", "historical-reference", "Historical Stanhope gig number 3915 reference drawing", "reusable", undefined, 1920, 1423),
  "workshop.ami-legacy.history.phaeton": workshopMedia("ami-legacy/historical/phaeton-651a.webp", "image", "Ami Legacy campaign packet", "historical-reference", "Historical phaeton number 651a reference drawing", "reusable", undefined, 1920, 1309),
  "workshop.ami-legacy.history.vis-a-vis": workshopMedia("ami-legacy/historical/vis-a-vis-3049.webp", "image", "Ami Legacy campaign packet", "historical-reference", "Historical vis-à-vis number 3049 reference drawing", "reusable", undefined, 1920, 1384),

  ...styleCardRecords("baseline"),
  ...styleCardRecords("anime"),
  ...styleCardRecords("baroque"),
  ...styleCardRecords("industrial"),

  "academy.banner.image": projectImage("hobfarm-courses-banner.jpg", "/academy/ and /projects/courses/", "academy-bridge", "HobFarm Academy courses banner"),
  "academy.banner.video": projectVideo("hobfarm-courses-banner-video.mp4", "hobfarm-courses-banner.jpg", "/academy/ and /projects/courses/", "academy-bridge-motion", "HobFarm Academy courses banner in motion"),
  "mtm.banner.image": projectImage("magazine-time-machine-banner.jpg", "/presents/magazine-time-machine/ and Presents indexes", "series-banner", "Magazine Time Machine archive banner"),
  "mtm.banner.video": projectVideo("magazine-time-machine-banner-video.mp4", "magazine-time-machine-banner.jpg", "/presents/magazine-time-machine/ and Presents indexes", "series-banner-motion", "Magazine Time Machine archive banner in motion"),

  "about.fractal-octopus.video": aboutVideo("Fractal%20Octopus.mp4", "supporting-philosophy", "Fractal octopus motion study", "active"),
  "about.glow.video": aboutVideo("about-glow-vid.mp4", "supporting-pitch", "Luminous HobFarm studio motion study", "active"),
  "about.hero.hayworth-avenue": {
    src: "/media/about/about-hero-hayworth-avenue-1920.webp",
    mediaType: "image",
    width: 1920,
    height: 1080,
    destination: "/about/",
    role: "author-landscape-photograph",
    alt: "Night photograph looking north along South Hayworth Avenue toward Beverly Boulevard, with parked cars and streetlights beneath trees",
    status: "active",
  },
  "about.hero.video": aboutVideo("about-hero-vid.mp4", "hero-candidate", "HobFarm About hero motion study", "unused"),

  "home.composition-lighting.one": homeImage("comp-lighting-1.png", "home-visual-showcase", "Composition and lighting comparison, first example", "active"),
  "home.composition-lighting.two": homeImage("comp-lighting-2.jpg", "home-visual-showcase", "Composition and lighting comparison, second example", "active"),
  "home.composition-lighting.two-video": homeVideo("comp-lighting-2.mp4", "comp-lighting-2.jpg", "home-visual-showcase", "Composition and lighting comparison in motion", "active"),
  "home.composition-lighting.three": homeImage("comp-lighting-3.png", "home-visual-showcase", "Composition and lighting comparison, third example", "active"),
  "home.drifter.image": homeImage("drifter.jpg", "project-candidate", "Drifter visual study", "unknown"),
  "home.drifter.video": homeVideo("drifter.mp4", "drifter.jpg", "project-candidate", "Drifter visual study in motion", "unknown"),
  "home.grimoire.image": homeImage("grimoire.jpg", "grimoire-candidate", "Grimoire visual study", "reusable"),
  "home.grimoire.video": homeVideo("grimoire.mp4", "grimoire.jpg", "grimoire-candidate", "Grimoire visual study in motion", "reusable"),
  "home.hillary.hero": homeImage("hillary-hobfarm-hero.png", "article-or-project-candidate", "Hillary HobFarm hero study", "unknown"),
  "home.hob-mascot": homeImage("hob-mascot.jpg", "home-and-about", "HobFarm mascot portrait", "active"),
  "home.hobbot.image": homeImage("hobbot.jpg", "project-candidate", "Hobbot visual study", "unknown"),
  "home.hobbot.video": homeVideo("hobbot.mp4", "hobbot.jpg", "project-candidate", "Hobbot visual study in motion", "unknown"),
  "home.site-banner": homeImage("hobfarm-web-banner.png", "site-banner-candidate", "HobFarm website banner", "reusable"),
  "home.hero.poster": homeImage("homepage-hero-poster.png", "article-media", "HobFarm homepage hero poster", "active"),
  "home.hero.video": homeVideo("homepage-hero.mp4", "homepage-hero-poster.png", "article-media", "HobFarm homepage hero video", "active"),
  "home.og-image": homeImage("og-image.jpg", "social-preview-candidate", "HobFarm social preview image", "duplicate-candidate"),
  "home.provider-logo.z-ai": homeImage("overview-z-ai-developer-document-logo.svg", "home-provider-strip", "Z.AI provider logo", "active"),
  "home.style-range.one": homeImage("style-range-1.png", "home-visual-showcase", "HobFarm style range example one", "active"),
  "home.style-range.two": homeImage("style-range-2.png", "home-visual-showcase", "HobFarm style range example two", "active"),
  "home.style-range.three": homeImage("style-range-3.png", "home-visual-showcase", "HobFarm style range example three", "active"),
  "home.style-range.four": homeImage("style-range-4.jpg", "home-visual-showcase", "HobFarm style range example four", "active"),
  "home.style-range.five": homeImage("style-range-5.jpeg", "home-visual-showcase", "HobFarm style range example five", "active"),
  "home.legacy-stylefusion.image": homeImage("stylefusion.jpg", "workshop-notes-candidate", "Early style-translation study", "reusable"),
  "home.legacy-stylefusion.video": homeVideo("stylefusion.mp4", "stylefusion.jpg", "workshop-notes-candidate", "Early style-translation study in motion", "reusable"),
  "home.technique.flat": homeImage("technique-flat.webp", "home-visual-showcase", "Flat rendering technique study", "active"),
  "home.technique.lineart": homeImage("technique-lineart.png", "home-visual-showcase", "Line-art rendering technique study", "active"),
  "home.technique.painterly": homeImage("technique-painterly.jpg", "home-visual-showcase", "Painterly rendering technique study", "active"),
  "home.technique.photo": homeImage("technique-photo.png", "home-visual-showcase", "Photographic rendering technique study", "active"),
} as const satisfies Record<string, MediaRecord>;

export type StyleCardMediaId = `workshop.style-card.${"baseline" | "anime" | "baroque" | "industrial"}.${"record" | "one" | "two" | "video"}`;
export type MediaId = keyof typeof mediaRegistry | StyleCardMediaId;

export function getMedia(id: MediaId): MediaRecord {
  return (mediaRegistry as Record<string, MediaRecord>)[id];
}

export function getMediaGroup(prefix: string): Array<[MediaId, MediaRecord]> {
  return (Object.entries(mediaRegistry) as Array<[MediaId, MediaRecord]>).filter(([id]) =>
    id.startsWith(prefix),
  );
}

export const projectHeroMedia = {
  stylefusion: { image: "stylefusion.banner.image", video: "stylefusion.banner.video" },
  courses: { image: "academy.banner.image", video: "academy.banner.video" },
  "hobfarm-tv/magazine-time-machine": { image: "mtm.banner.image", video: "mtm.banner.video" },
} as const satisfies Record<string, { image: MediaId; video: MediaId }>;

export function getProjectHeroMedia(projectId: string) {
  const ids = projectHeroMedia[projectId as keyof typeof projectHeroMedia];
  return ids ? { image: getMedia(ids.image), video: getMedia(ids.video) } : undefined;
}

function processImage(folder: "book" | "motion", file: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/process/${folder}/${file}`), mediaType: "image", destination: "/workshop/stylefusion/", role, alt, status: "active" };
}

function processVideo(folder: "book" | "motion", file: string, poster: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/process/${folder}/${file}`), poster: cdn(`pages/process/${folder}/${poster}`), mediaType: "video", destination: "/workshop/stylefusion/", role, alt, status: "active" };
}

function processDocument(folder: "book" | "motion", file: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/process/${folder}/${file}`), mediaType: "document", destination: "/workshop/stylefusion/", role, alt, status: "active" };
}

function characterImage(file: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/process/fashion/${file}`), mediaType: "image", destination: "/workshop/character-mannequin/", role, alt, status: "active" };
}

function characterVideo(file: string, poster: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/process/fashion/${file}`), poster: cdn(`pages/process/fashion/${poster}`), mediaType: "video", destination: "/workshop/character-mannequin/", role, alt, status: "active" };
}

function characterDocument(file: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/process/fashion/${file}`), mediaType: "document", destination: "/workshop/character-mannequin/", role, alt, status: "active" };
}

function conceptImage(file: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/home/concept/${file}`), mediaType: "image", destination: "/workshop/character-mannequin/", role, alt, status: "active", futureCanonicalKey: `workshop/character-mannequin/generic-37/${file}` };
}

function conceptVideo(file: string, poster: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/home/concept/${file}`), poster: cdn(`pages/home/concept/${poster}`), mediaType: "video", destination: "/workshop/character-mannequin/", role, alt, status: "active", futureCanonicalKey: `workshop/character-mannequin/generic-37/${file}` };
}

function avatarHostPlaceholder(mediaType: "video" | "document", file: string, role: string, alt: string): MediaRecord {
  return {
    src: "",
    mediaType,
    destination: "/workshop/avatar-host/",
    role,
    alt,
    status: "registered",
    futureCanonicalKey: `workshop/character-mannequin/avatar-host-system/${file}`,
  };
}

function workshopMedia(
  file: string,
  mediaType: MediaType,
  destination: string,
  role: string,
  alt: string,
  status: MediaStatus,
  poster?: string,
  width?: number,
  height?: number,
): MediaRecord {
  return {
    src: cdn(`workshop/${file}`),
    poster: poster ? cdn(`workshop/${poster}`) : undefined,
    mediaType,
    width,
    height,
    destination,
    role,
    alt,
    status,
    futureCanonicalKey: `workshop/${file}`,
  };
}

function workshopImage(
  file: string,
  destination: string,
  role: string,
  alt: string,
  width: number,
  height: number,
  status: MediaStatus = "active",
): MediaRecord {
  return {
    src: cdn(`workshop/${file}`),
    mediaType: "image",
    width,
    height,
    destination,
    role,
    alt,
    status,
  };
}

function workshopMethodImage(file: string, alt: string): MediaRecord {
  return {
    src: `/media/workshop/production-method/${file}`,
    mediaType: "image",
    width: 1254,
    height: 1254,
    destination: "/workshop/#method",
    role: "method-stage",
    alt,
    status: "active",
  };
}

function workshopProgramIndexImage(file: string, destination: string, alt: string): MediaRecord {
  return {
    src: `/media/workshop/program-index/${file}`,
    mediaType: "image",
    width: 1360,
    height: 1020,
    destination,
    role: "program-index",
    alt,
    status: "active",
  };
}

function workshopRouteCardImage(file: string, destination: string, alt: string): MediaRecord {
  return {
    src: `/media/workshop/route-cards/${file}`,
    mediaType: "image",
    width: 1360,
    height: 1020,
    destination,
    role: "workshop-route-card",
    alt,
    status: "active",
  };
}

function beforeAfterMedia(
  file: string,
  mediaType: "image" | "video",
  role: string,
  alt: string,
  poster?: string,
  width?: number,
  height?: number,
): MediaRecord {
  return {
    src: cdn(`workshop/before-and-after/scene/${file}`),
    poster: poster ? cdn(`workshop/before-and-after/scene/${poster}`) : undefined,
    mediaType,
    width,
    height,
    destination: "/workshop/before-and-after/",
    role,
    alt,
    status: "active",
  };
}

function styleCardRecords(slug: "baseline" | "anime" | "baroque" | "industrial") {
  const destination = "/workshop/workshop-notes/";
  return {
    [`workshop.style-card.${slug}.record`]: { src: cdn(`pages/home/style-card/${slug}.txt`), mediaType: "document", destination, role: "text-record", alt: `${slug} style-translation text record`, status: "active" },
    [`workshop.style-card.${slug}.one`]: { src: cdn(`pages/home/style-card/${slug}1.jpg`), mediaType: "image", destination, role: "result", alt: `${slug} style-translation result one`, status: "active" },
    [`workshop.style-card.${slug}.two`]: { src: cdn(`pages/home/style-card/${slug}2.jpg`), mediaType: "image", destination, role: "result", alt: `${slug} style-translation result two`, status: "active" },
    [`workshop.style-card.${slug}.video`]: { src: cdn(`pages/home/style-card/${slug}-vid.mp4`), poster: cdn(`pages/home/style-card/${slug}1.jpg`), mediaType: "video", destination, role: "motion-result", alt: `${slug} style-translation motion result`, status: "active" },
  } satisfies Record<string, MediaRecord>;
}

function projectImage(file: string, destination: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/projects/images/${file}`), mediaType: "image", destination, role, alt, status: "registered" };
}

function projectVideo(file: string, poster: string, destination: string, role: string, alt: string): MediaRecord {
  return { src: cdn(`pages/projects/images/${file}`), poster: cdn(`pages/projects/images/${poster}`), mediaType: "video", destination, role, alt, status: "registered" };
}

function aboutVideo(file: string, role: string, alt: string, status: MediaStatus): MediaRecord {
  return { src: cdn(`pages/about/${file}`), mediaType: "video", destination: "/about/", role, alt, status };
}

function homeImage(file: string, role: string, alt: string, status: MediaStatus): MediaRecord {
  return { src: cdn(`pages/home/${file}`), mediaType: "image", destination: "home archive", role, alt, status };
}

function homeVideo(file: string, poster: string, role: string, alt: string, status: MediaStatus): MediaRecord {
  return { src: cdn(`pages/home/${file}`), poster: cdn(`pages/home/${poster}`), mediaType: "video", destination: "home archive", role, alt, status };
}
